# Generated by Django 5.0.6 on 2024-05-24 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeroport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Compagnie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pays_attache', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAvion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='avions/')),
                ('longueur_piste_necessaire', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Piste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('longueur', models.IntegerField()),
                ('aeroport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.aeroport')),
            ],
        ),
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.compagnie')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.typeavion')),
            ],
        ),
        migrations.CreateModel(
            name='Vol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilote', models.CharField(max_length=100)),
                ('date_heure_depart', models.DateTimeField()),
                ('date_heure_arrivee', models.DateTimeField()),
                ('aeroport_arrivee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='gestion.aeroport')),
                ('aeroport_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='gestion.aeroport')),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.avion')),
            ],
        ),
    ]
