# Generated by Django 5.0.6 on 2024-06-05 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeavion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='vol',
            name='aeroport_arrivee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivee_vols', to='gestion.aeroport'),
        ),
        migrations.AlterField(
            model_name='vol',
            name='aeroport_depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart_vols', to='gestion.aeroport'),
        ),
    ]
