# Generated by Django 5.0.6 on 2024-06-08 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_typeavion_image_alter_vol_aeroport_arrivee_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aeroport',
            table='aeroport',
        ),
        migrations.AlterModelTable(
            name='avion',
            table='avion',
        ),
        migrations.AlterModelTable(
            name='compagnie',
            table='compagnie',
        ),
        migrations.AlterModelTable(
            name='piste',
            table='piste',
        ),
        migrations.AlterModelTable(
            name='typeavion',
            table='typeavion',
        ),
        migrations.AlterModelTable(
            name='vol',
            table='vol',
        ),
    ]
